-- 환불 재시도 이력 테이블
CREATE TABLE IF NOT EXISTS REFUND_RETRY_HISTORY (
    RETRY_ID INT AUTO_INCREMENT PRIMARY KEY,
    DEPOSIT_ID INT NOT NULL,
    ATTEMPT_NUMBER INT NOT NULL DEFAULT 1,
    ATTEMPT_DATE DATETIME NOT NULL,
    RETRY_STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    NEXT_RETRY_DATE DATETIME,
    ERROR_CODE VARCHAR(50),
    ERROR_MESSAGE VARCHAR(500),
    REFUND_AMOUNT INT,
    REFUND_REASON VARCHAR(200),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME,
    
    CONSTRAINT FK_REFUND_RETRY_DEPOSIT FOREIGN KEY (DEPOSIT_ID) REFERENCES DEPOSIT(DEPOSIT_ID),
    INDEX IDX_REFUND_RETRY_DEPOSIT (DEPOSIT_ID),
    INDEX IDX_REFUND_RETRY_STATUS (RETRY_STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- RETRY_STATUS possible values: PENDING, IN_PROGRESS, FAILED, SUCCESS
